### ISSUE TITLE
[deploySummary] Move out of Peril, into Horizon

### ISSUE THREAD

**Issue by mzikherman** [artsy/peril-settings#138]
This is currently a Peril rule, but wondering if it might make more sense as a Horizon function.

One downside is that it seems as though Peril comments disappear after the PR is merged, which definitely is not ideal.

While this type of 'nice' automation does make perfect sense in Peril/Danger, it can be a bit confusing to develop on and test. Additionally there seems to be some kinks left to work out (the deleting comment thing).

Since Horizon, which started to visualize release pipelines, is now expanding to do some automation around releases, maybe this enhancement (as it's explicitly about releases), makes sense to roll into there?

cc @joeyAghion @dblandin

**Comment by joeyAghion** [comment]
I don't understand the comment disappearance--that seems like a bug.

One way this summary _aligns_ with Peril is that Peril already has to reevaluate PRs on every change. The set of PRs included in a release can grow as more merges and builds happen, so it works nicely that Peril can re-run and update its comment.

If you _did_ want to add a list of PRs into the release via Horizon the [`DeployService`](https://github.com/artsy/horizon/blob/master/app/services/deploy_service.rb) is probably where  you'd do it. Happy to talk more about a strategy for tha.

**Comment by mzikherman** [comment]
Coming back to this, so far Peril has been solid, except for the disappearing comment after merge. That's less of an issue though.

There's also some benefit to having the infrastructure to already receive web hooks when things change. Having the initial comment contain the list of PR's generated by Horizon is fine but not realistic for deploy PR's that sit open for a while.

Then, adding specific logic to check + update a deploy PR summary in Horizon during it's cron run, is ok-ish, but starts to feel weirder.

I'll close this for now!
