### ISSUE TITLE
RFC: Validate PR description Changelogs on Eigen

### ISSUE THREAD

**Issue by MounirDhahri** [artsy/peril-settings#182]
## Proposal:

Whenever a PR is created in Eigen and is ready, check the PR description changelog changes. The outcome of this should be:
- Validate the changelog changes and notify the author if something is wrong
- Clear feedback about all the changes

### Examples:
<details>
  <summary>Invalid changelog</summary>

❌ **An error occurred while validating your changelog, please make sure you provided a valid changelog**
</details>

<details>
  <summary>Valid changelog with changes</summary>

#### Cross-platform user-facing changes
- This is a cross platform user-facing change
#### iOS user-facing changes
- An update affecting only iOS
</details>

<details>
  <summary>Valid changelog with no changes</summary>

✅ **No changelog changes**
</details>

## Reasoning

The rule should enforce all of the invariants described in [this RFC](https://github.com/artsy/eigen/issues/4499) and log all the changelog entries that will be added (for debugging purposes in case something goes wrong).

## Exceptions:
- This rule will be running **only on Eigen**
- This rule should be only turned on when the related work is enabled in Eigen. We can achieve that by checking for a string in the PR body `#run_new_changelog_check`.

## Resolution:
- Merge this https://github.com/artsy/peril-settings/pull/183

**Comment by kajatiger** [comment]
I like this idea! Can we implement eigen-only rules in peril?

**Comment by MounirDhahri** [comment]
@kajatiger yes, we can do that, this is how I am doing it https://github.com/artsy/peril-settings/blob/66d05d5cea5207e547e8966d73a42f7bfb163767/org/allPRs.ts#L231-L236

**Comment by damassi** [comment]
Could one use Eigen's local [`Danger` file](https://github.com/artsy/eigen/blob/master/Dangerfile.circle.rb) rather than making changes to peril?

**Comment by MounirDhahri** [comment]
@damassi makes complete sense, I didn't know danger supports local configurations. I will check it now

**Comment by dblandin** [comment]
> makes complete sense, I didn't know danger supports local configurations. I will check it now

Here are some examples of rules that are defined in specific repos but executed by Peril:

https://github.com/artsy/peril-settings/blob/master/peril.settings.json#L22-L41

**Comment by MounirDhahri** [comment]
I will this for now since I moved the logic to be inside Eigen 🙌 Thanks everyone for the feedback. 
If anyone is interested in the implementation details. Here is it: https://github.com/artsy/eigen/pull/4815
