### ISSUE TITLE
RFC: Add a weekly scheduled task which shows what has changed in our GraphQL APIs

### ISSUE THREAD

**Issue by orta** [artsy/peril-settings#51]
## Proposal:

Migrate from [graphql-slack-updater](https://github.com/artsy/graphql-slack-updater) to a weekly peril job.

## Reasoning

* Consolidation of tooling
* Less code
* Easier for others to contribute
* Moves from running on CI to in-memory ( https://github.com/artsy/graphql-slack-updater/issues/1 )

## Exceptions:

None, as each GraphQL server would need to be added individually. So start with metaphysics, and wait depending on how far stitching is along.

## Additional Context:

Will be the first time that Peril uploads something to S3, so will need to add support for that..

For devs: `GitHub event ID: ac11df00-0366-11e8-991a-ee17164aa737`

**Comment by damassi** [comment]
👍 from me assuming the setup / takedown process is well-documented.

**Comment by orta** [comment]
It'd probably end up as a single file of JS, so should be pretty easy to grok. The CLI version was under 100 LOC, so shouldn't be too bad I expect.

**Comment by orta** [comment]
This is in with https://github.com/artsy/peril-settings/pull/84
