### ISSUE TITLE
[RFC] Provide more automatic Jira integration

### ISSUE THREAD

**Issue by orta** [artsy/peril-settings#74]
## Proposal:

Your work in GitHub should automate Jira tickets, it should be simple and reflect how we are already working. 

The simplest proposal I have is to allow Peril to take;

1. Commit messages with shorthand IDs e.g.` "PLAT-89 Turns on the flabberwocky"`
2. Shorthand IDs or URLs to jira links in a body

Then use those references to transition the referenced tickets to the "In Progress" state, and to leave a comment passing the link to the PR while the PR is open.

Then when the PR is merged, update the status to "In QA".

## Reasoning

Jira is an additional place to be duplicating work, as much of that as possible should be automated.

## Exceptions:

I don't think we have complicated enough workflows today, but it's possible in the future we'll need to handle this a bit more like how GitHub does "fixes #123" instead. That can be handled when we get there.

**Comment by ashfurrow** [comment]
Cool! I really like this idea. A few pieces of feedback: 

- It might be wise to have a permissive format for commit messages – some teams use the `"[Push Notifications] Fixes whatever..."` format, for example. We could use that format for Jira tickets.
- GitHub uses visual design to show when something like "fixes #123" in a PR body will close an issue. We might want Peril to comment on the PR with a message like "Merging this PR will move PLATFORM-89 to Review column", with PLATFORM-89 turned into a link to that ticket.
- Different teams use different columns in Jira, so our implementation might have to handle moving to different columns based on which project the ticket is in.

**Comment by orta** [comment]
> It might be wise to have a permissive format for commit message

It's totally permissive, there's no attempt at forcing a format - I think `[PLAT-123] did a thing` would not pass the regex though. Could add an extra regex for that too.

> GitHub uses visual design to show when something like "fixes #123" ...

We could have a "Synced with Jira" label, that means less Peril noise and easy to know that it's happening.

> Different teams use different columns in Jira

Great, will convert the check into an includes in an array instead of string matching 👍

**Comment by orta** [comment]
Sub-tasks maybe? Or we can figure a way to make the message not indicate that it should close the ticket. It's very malleable, and the aim is to map to existing behavior, not necessarily define it if possible.
